# Generated by Django 3.1.1 on 2020-09-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='card',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
