# Generated by Django 3.1.1 on 2020-09-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='card',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
