# Generated by Django 3.1.1 on 2020-09-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postit', '0003_auto_20200920_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='y',
            field=models.FloatField(default=0),
        ),
    ]
